### ISSUE TITLE
Ремонт входной двери

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#10]
* На двери сейчас используется внешний навесной замок, который надо поменять на встроенный замок. *Внимание:* при замене замка копию ключа необходимо отдать Владимиру Слугину и другим участникам хакерспейса, у которых уже есть ключ.

* Наложить патчи на дверь, дабы аккуратно заделать дыру от старого кодового замка.

* Покрасить дверь с внешней стороны и стену вокруг неё.  Если правильно помню, @gymlyg предложил купить краску под цвет двери.

* Оформить дверь с внешней стороны -- предлагаю нарисовать на ней [персонажей](https://commons.wikimedia.org/wiki/File:Alien_pixel.png) из Space Invaders.  Баллончики с краской есть.

**Comment by artyom-poptsov** [comment]
Дверь покрашена, дыры в ней заделаны.

**Comment by ghost** [comment]
В дверь был установлен суперсовременный электронный замок. Осталось лишь грамотно его настроить.
