### ISSUE TITLE
Решить проблему со SpaceAPI

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#12]
Хакерспейс использует [SpaceAPI](http://spaceapi.net/) для публикации информации о нас и статусе.  К сожалению, уже долгое время (год или больше) сервис работает с перебоями.  Недавно у SpaceAPI [появился форк](https://groups.google.com/d/topic/cadr-hackerspace/c-LIZwtoNFE/discussion) (https://spacedirectory.org/) -- надо рассмотреть возможность миграции.

**Comment by ghost** [comment]
Проблема со SpaceAPI решена - статус хакерспейса можно наблюдать в реальном времени.
