### ISSUE TITLE
Починить главный хакерспейсный ноутбук

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#13]
Ноутбук периодически самопроизвольно выключается и глючит со страшной силой.  Скорее всего, посыпался жёсткий диск, но надо проверить.  Если проблема в диске, то можно купить диск на замену.

**Comment by ghost** [comment]
Вследствии эксперимента было выяснено, что память на ноутбуке оказалась исправной. Нужно попробовать слить остатки уцелевших данных в безопасное хранилище, и восстановить диск.

**Comment by artyom-poptsov** [comment]
Пробовал заменить HDD в ноутбуке на новый (HGST SATA 2.0 500GB), но ноутбук его не видит (он даже не раскручивается.)  Есть два возможных объяснения:
1. Ноутбук поддерживает только SATA 1.0 (в интернете [можно найти описание](https://forum.ts.fujitsu.com/forum/viewtopic.php?t=40614) подобных проблем)
2. HDD нехватает питания.  Родной диск был 5V 0.48А, тогда как купленный был 5V 0.8A.  Хотя при проверке с HDD 5V 0.55A, диск тоже не заработал.

Фото родного HDD прилагаю.

![vint](https://user-images.githubusercontent.com/1094402/29000518-d205d2fe-7a75-11e7-9a2f-42deb7bd7bac.png)

**Comment by artyom-poptsov** [comment]
В ноутбук @FurryCyanFox был поставлен Б/У диск из другого ноутбука, который не использовался.

В качестве системы был установлен Debian GNU/Linux с XFCE.  Осталось перенести данные со старого диска на более новый.  В понедельник займусь, если время будет.

**Comment by artyom-poptsov** [comment]
У ноутбука, похоже, опять вышел из строя HDD.
