### ISSUE TITLE
Поменять дату основания хакерспейса на странице сообщества в vk.com

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#14]
Необходимо поменять дату основания хакерспейса на странице сообщества в vk.com: вместо "21 May 2013" нужно написать "25 May 2013" (т.к. за дату основания хакерспейса [было решено](https://groups.google.com/d/topic/cadr-hackerspace/0lRHly8mg6A/discussion) принять дату аренды первого помещения.)

**Comment by donyshow** [comment]
Ok! Готово!
