### ISSUE TITLE
Повесить монитор

### ISSUE THREAD

**Issue by ghost** [cadrspace/maintenance#16]
За little-grebe  пока что невозможно нормально работать, вследствии энтропии на столе, и неудобно поставленного монитора. На cadr е есть монитор, с креплением на стену. Предлагаю закрепить его.

**Comment by FurryCyanFox** [comment]
Наконец пофиксил энтропию. Вызвал костыльного единорога. Монитор невозможно повесить без спецэффектов со стороны проводки. Но был найден обходной путь, и все работает.  Пока что на столе можно жить спокойно.
