### ISSUE TITLE
Повесить дополнительные полки

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#2]
Можно опустить маркерную доску ниже, поверх неё повесить ещё одну полку. На самую нижнюю секцию полки можно повесить освещение доски (например, светодиодную лампу.)

Также можно повесить дополнительные полки в монтажно-компьютерной зоне -- над имеющимися полками ещё есть место. 

Размер полок в монтажно-компьютерной зоне:
* 1150x370x15 мм, глубина: 255 мм
В компьютерно-монтажной зоне:
* 1160x220x15 мм, глубина 225мм

Ещё нужно купить 10 уголков и прочий крепёж.

**Comment by artyom-poptsov** [comment]
Вариант с перемещением маркерной доски на встрече в субботу решено не делать, вместо этого вешаем полку сразу над доской.

Материалы можно купить в OBI.  Например:
- [Фанера сорт 4/4 1525х1525х15мм, 599 р.](https://www.obi.ru/fanera-plity-dsp-dvp/fanera-fk-sort-4-4-1525kh1525kh15mm/p/2504637)
- [Фанера ФК сорт 3/4 шлифованная 1525х1525х12мм, 513 р.](https://www.obi.ru/fanera-plity-dsp-dvp/fanera-fk-sort-3-4-shlifovannaya-1525kh1525kh12mm/p/2371094)

@donyshow вызвался помочь с покупкой и доставкой материалов, а также сборкой полок.

**Comment by artyom-poptsov** [comment]
Вместе с @donyshow сегодня купили материалы и крепёж, затем завезли купленное в НРТК.  Временно всё лежит в комнате вахтёров.  Вахтёр, который дежурит сегодня, обещал предупредить следующую смену по поводу данных вещей.  Завтра перенесу их в хакерспейс.

Большое спасибо @donyshow за помощь в выборе материалов и доставке всего до места назначения.

Думаю, в субботу (или, может быть, даже раньше) начнём процесс сборки полок.

**Comment by donyshow** [comment]
Для подсветки маркерной доски решили использовать светодиодную ленту, которая как раз долго лежала и ждала своего часа!

**Comment by artyom-poptsov** [comment]
Сегодня пошкурили листы фанеры для полок.  Сборку и установку полок договорились начать в среду.

**Comment by artyom-poptsov** [comment]
На прошлой неделе в среду полностью собрали одну полку.  Скорее всего, в среду на следующей неделе будем вешать.

**Comment by artyom-poptsov** [comment]
Одна полка повешена над доской, на неё перенесены книги и журналы.

**Comment by artyom-poptsov** [comment]
Вчера вместе с @gymlyg собрана ещё одна полка, сегодня будем вешать на стену.

**Comment by artyom-poptsov** [comment]
Повесили ещё одну полку вместе с Леонидом Х. в М-К зоне.

**Comment by artyom-poptsov** [comment]
Вчера @gymlyg собрал две полки для К-М зоны.

Прикрепил уголки для одной из полок.  Начал собирать ещё одну полку для М-К зоны.

У нас заканчиваются уголки.  Пример уголка приведён ниже.  @gymlyg, если у тебя будет возможность, то посмотри уголки в OBI, или любом строительно магазине.  Если смогу, то тоже гляну.

![img_20170712_205427](https://user-images.githubusercontent.com/1094402/28137582-7e39a524-6756-11e7-8541-f4a8d5f8e219.jpg)

**Comment by artyom-poptsov** [comment]
Купил вчера 12 уголков, аналогичных тем, что мы использовали до этого для полок.

**Comment by artyom-poptsov** [comment]
Вместе с Леонидом Х. повесили полку в М-К зоне.  Немного ошибся с расположением полки при замерах, поэтому она смещена вправо; тем не менее, функцию выполняет.

Ещё две полки ожидают своей очереди.

**Comment by artyom-poptsov** [comment]
[Повесил полку](https://twitter.com/cadrspace/status/887669835177627648) над входной дверью.  Рядом планирую повесить ещё одну, но стена очень плохо сверлится -- хороший бетон попался.

**Comment by artyom-poptsov** [comment]
Последние несколько дней сверлил отверстия для второй полки над стеллажом. В итоге, отверстия больше похожи на дырки, но свою функцию (удержание полки на стене), думаю, будут выполнять.  Лишние дырки в стене вместе с Андреем Кулагиным замазал цементным раствором, разведённым из того, что нашёл в мешке, который принёс @gymlyg.

Оставшийся цементный раствор использовал для замазывания прочих дырок и щелей в дверном косяке и везде, где мог их найти.

Спасибо Андрею за подсказки по созданию нужной консистенции раствора.

**Comment by artyom-poptsov** [comment]
Полка над стеллажом повешена и используется.  Остался материал для ещё одной полки, которую можно будет повесить в М-К зоне.

**Comment by artyom-poptsov** [comment]
@gymlyg собрал ещё одну полку для М-К зоны.

**Comment by artyom-poptsov** [comment]
Все полки собраны и подмонтированы к стенам.  Неподмонтированных более не осталось.
