### ISSUE TITLE
Купить дрель

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#3]
В хакерспейсе чувствуется острая дрельная недостаточность. Её можно исправить путём покупки электродрели. Из марок сотрудниками НРТК была предложена марка BOSH.

**Comment by artyom-poptsov** [comment]
В комиссионном магазине куплена Б/У дрель в хорошем состоянии пермской фирмы "Ритм", модель вроде [МЭС-600-ЭР](http://www.baikalot.ru/rhithm/drill/index.files/600.htm), за 1000 р., плюс переключатель к дрели на замену сломанного за 200 р.

Дрель обычная, не ударная, обладает возможностью реверса и регулировки скорости вращения.  Для каждодневных работ вполне подойдёт.

1000 р. на покупку дрели пожертвовано Юрием А., 200 р. пожертвованы мной.  @gymlyg заменил переключатель на новый.

Плюс купил сверло по бетону на 5 мм. за 50 р. (хотя надо было на 6 мм.  :-) )  При возможности куплю и на 6 мм.

**Comment by donyshow** [comment]
Good job )
