### ISSUE TITLE
Починить МФУ

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#33]
* Купить драм-картридж
* Купить тонер

**Comment by artyom-poptsov** [comment]
Запчасти закуплены.

**Comment by donyshow** [comment]
Ждем поставку.

**Comment by artyom-poptsov** [comment]
Картридж есть!  Работает в тестовом режиме.  Тонера в нём мало, надо будет заправить после испытательного строка.

**Comment by artyom-poptsov** [comment]
Принтер работает.  Были виртуальные "замятия" бумаги при взятии из нижнего лотка, однако проблема похоже была исправлена чисткой принтера от пыли.
