### ISSUE TITLE
Сделать отдельную линию на 12В

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#39]
Сделать отдельную линию на 12В для подключения маломощных приборов и светильников, дабы не плодить отдельные БП для каждого случая (как мы сделали с новой лампой в МК-зоне.)  Идея предложена Петром Третьяковым -- думаю, что она здравая.

**Comment by ghost** [comment]
Идея хоть и здравая, но труднореализуемая. Также, не уверен в целесообразности данной линии
