### ISSUE TITLE
Приобрести светодиодную ленту 2+ метров

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#41]
Необходима светодиодная лента белого холодного света не менее 2-х метров для организации футуристичного освещения наших CADR'ов.

**Comment by ghost** [comment]
Белая светодиодная лента, в обьеме 2 метра, была приобретена @gymlyg и доставлена на первую площадку хакерспейса. Осталось придумать мега проект футуристичного CADR'о светильника

**Comment by artyom-poptsov** [comment]
Уже даже использовали 1м на освещение М-К зоны.
