### ISSUE TITLE
Подключить интернет на второй площадке

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#46]

**Comment by ghost** [comment]
Интернет по выделенной линии стоит крайне дорого(900 рублей за скорость в 10 мегабит в секунду). Предлагаю использовать 4g модем и роутер с USB разьемом для раздачи интернета. Оператор - Yota, так как там самые выгодные условия(550 рублей в месяц, за скорость около 60 мегабит в секунду, примерная скорость 4G). Роутер уже есть, осталось его прошить, для поддержки USB модемов. Модем можно найти на Авито.
