### ISSUE TITLE
Подготовка стенда к мероприятию

### ISSUE THREAD

**Issue by gymlyg** [cadrspace/maintenance#70]
Задачи-подзадачи для подготовки стенда к одному из мероприятий.

**Comment by gymlyg** [comment]
Игровое табло.
Есть собранный на клее макет.
Надо:

- собрать его понадежнее
- обновить софт при необходимости

**Comment by gymlyg** [comment]
3Д принтер. Что и как с ним - не знаю. Обновите коммент - кто в курсе.

**Comment by gymlyg** [comment]
Подготовить необходимые вещи:

- стол (столы)
- стул (стулья)
- шатер (навес, палатка)
- удлинители
- инструменты
- остальное

**Comment by artyom-poptsov** [comment]
3D-принтер работает, насколько помню.  Надо его погонять ещё, посмотреть.
