### ISSUE TITLE
Повесить светодиодную лампу над маркерной доской

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#8]
Лампу можно прикрепить к нижней части полки над доской, когда будет решена задача #2.

Светодиодная лампа может быть сделана из светодиодной ленты, которая уже есть в хакерспейсе.

**Comment by artyom-poptsov** [comment]
@donyshow подключил и повесил светодиодную ленту, за что ему большое спасибо.

**Comment by donyshow** [comment]
А еее!
