### ISSUE TITLE
Сделать вытяжку в монтажно-компьютерной зоне

### ISSUE THREAD

**Issue by artyom-poptsov** [cadrspace/maintenance#81]
Вытяжка должна идти либо в трубу вытяжки, которая там имеется.

**Comment by madnessman666** [comment]
### Обновление: 
C появлением лазерного станка вытяжка в основном вытягивает из станка. Паяльные зоны остались совсем без вытяжки. 

### Решение: 
1. Поставить тройник и подключить станок и паяльную зону к этому тройнику. 

### Дополнительно: 
На вытяжку с паяльной зоны (да и на вытяжку от станка) было бы неплохо поставить обратный клапан, чтобы предотвратить обратную тягу.

**Comment by madnessman666** [comment]
Сделано
